### ISSUE TITLE
fine adjustments in the internationalization

### ISSUE THREAD

**Issue by salgado** [igarape/copcast-admin#103]
There are some buttons that are not internationalized

**Comment by ebadran** [comment]
There are still a few adjustments to be made.

In the Portuguese version, the date needs to be switched from MM/DD/YYYY to DD/MM/YYYY.

In the English version, there are several adjustments needed, as indicated in the screen shots:

![screen shot 2015-10-21 at 18 42 46](https://cloud.githubusercontent.com/assets/12832304/10649760/75b378a8-7824-11e5-94b6-f057704ca883.png)
![screen shot 2015-10-21 at 18 31 08](https://cloud.githubusercontent.com/assets/12832304/10649779/91736f62-7824-11e5-8ed1-97fc9b96c269.png)
