### ISSUE TITLE
[History] store the data period state during navigation

### ISSUE THREAD

**Issue by salgado** [igarape/copcast-admin#106]
(1) navigate to the history screen
(2) select an user and a date period
(3) navigate to other screen 
(4) navigate back to the history screen
RESULT: The history screen remembers the user, but not the period

**Comment by salgado** [comment]
Request from Santa Marta tests.

**Comment by brunosiqueira** [comment]
@martelli you did this, right?

**Comment by brunosiqueira** [comment]
Not storing the date period. Only the user

**Comment by martelli** [comment]
I did not work on this issue.

**Comment by martelli** [comment]
@brunosiqueira Can you give some light here? :D

**Comment by brunosiqueira** [comment]
@martelli I updated the description. Low priority though
