### ISSUE TITLE
[App] During the actual tests one of the cells has stopped with erro: "Copcast Stopped", follows the splunk log.

### ISSUE THREAD

**Issue by salgado** [igarape/copcast-admin#109]
View the full details of this error at Splunk MINT

Error Message

java.lang.RuntimeException: An error occured while executing doInBackground()

Where

VideoRecorderService.java:197

Short Stacktrace

0	java.lang.RuntimeException: An error occured while executing doInBackground()
1	at android.os.AsyncTask$3.done(AsyncTask.java:300)
2	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
3	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
4	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
5	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
6	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
7	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
8	at java.lang.Thread.run(Thread.java:841)
9	Caused by: java.lang.IllegalStateException
10	at android.media.MediaRecorder.start(Native Method)
11	at org.igarape.copcast.service.VideoRecorderService$MediaPrepareTask.doInBackground(VideoRecorderService.java:197)
12	at org.igarape.copcast.service.VideoRecorderService$MediaPrepareTask.doInBackground(VideoRecorderService.java:192)
13	at android.os.AsyncTask$2.call(AsyncTask.java:288)
14	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
15	... 4 more

**Comment by brunosiqueira** [comment]
closing this issue. The code changed a lot and it looks more stable now. Let's reopen it if we receive the error again via Splunk
