### ISSUE TITLE
Fix audio bugs when receiving upload

### ISSUE THREAD

**Issue by salgado** [igarape/copcast-admin#123]
file date: 2015-08-01T02:35:04.000Z
POST /videos/lvianasd 201 61.180 ms - 7
STREAMERR: Wont process audio. Corrupted video. Moving raw file
Cannot process audio: Cannot find ffmpeg
STREAMERR: Cannot find ffmpeg
Uploaded file: /tmp/4e095cb0947c795430111cdad1472440
file date: 2015-08-01T02:37:03.000Z
POST /videos/lvianasd 201 70.249 ms - 7

**Comment by brunosiqueira** [comment]
this bug shows that ffmpeg was not installed in the machine
