### ISSUE TITLE
Reports of Use

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#125]
The admin interface should also present metrics of its use 
- One report for each precinct + an aggregated report for each department (DoCS and DPS).
Data Points that may be included in the CopCast Log Report:
 - Number of officers initiating missions;
 - Number of hours of recorded footage;
 - Average length of recordings;
 - Median length of recordings;
 - Hi-Res heatmap of the period for each precinct (in PDF or PNG).

**Comment by ebadran** [comment]
não tinha visto que este issue já existia. Fiz um outro issue sobre o report (#158), portanto estão repetidos.
