### ISSUE TITLE
Increase security with video playing

### ISSUE THREAD

**Issue by salgado** [igarape/copcast-admin#128]
In the History screen, the visualization of the recorded videos are not authenticated. 
We can not pass the authentication header when the URL is directly accessed from 

      <video src="http://xxxxx" />
 
Study a new way of accessing the videos and guarantee the security.

**Comment by martelli** [comment]
A solution has been implemented, where the token value is extracted from the cookie, if the 'authorization' header is not present. Full implementation depends on #172, which is under debate.
