### ISSUE TITLE
Accessing from iPad, the menu does not show

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#156]
Accessing via chrome

![image](https://cloud.githubusercontent.com/assets/28031/10167386/3200bee2-66c0-11e5-936c-48acc8c0b14f.png)

**Comment by ebadran** [comment]
Bruno, se você achar útil, posso fazer um teste num tablet Motorola Xoom velho que eu tenho em casa.

**Comment by brunosiqueira** [comment]
@ebadran pode fazer o teste sim! Eu só preciso verificar amanhã se eu já enviei essa versão pro nosso servidor.
