### ISSUE TITLE
Cape Town Pilot Log Report

### ISSUE THREAD

**Issue by ebadran** [igarape/copcast-admin#158]
The Log Report will be generated automatically by the Smart Policing Application for each implementing agency (Traffic Police, VPUU, Building Security).

The following data Points may be included in the Log Report:

- Number of active officers users (users that have been assigned a smartphone);
- Number of missions initiated (missions greater than 30 minutes);
- Average and median length of recordings;
- Number of hours of recorded footage. Number of hours of streamed footage;
- Number of flags;
- Number of personnel accessing the admin system (Audit log);
- How much total footage, by time and number of distinct pieces, has each person viewed in the last week;
- Exact information on what videos have been exported within the last week;
- Number of traffic incidents reported with the Smart Policing Digital Incident Reporting Form, aggregated by the gravity of the incidents;
- Number of incidents of police use of force reported with the Smart Policing Digital Incident Reporting Form, aggregated by the gravity of the incidents.

Any person with Admin-level of access to the system may generate the report on demand.

**Comment by brunosiqueira** [comment]
@ebadran I have a question regarding two fields:
 - Average and median length of recordings: length of each video piece?
 - How much total footage, by time and number of distinct pieces, has each person viewed in the last week

**Comment by martelli** [comment]
"Number of times mission was stopped" is empty.
"Number of missions initiated" not in the log.
"Average and median length of recordings" is still valid?
"Number of personnel accessing the admin system (Audit log)" - missing value
"How much total footage, by time and number of distinct pieces, has each person viewed in the last week" - missing
"Exact information on what videos have been exported within the last week" - export not implemented
"Number of incidents of police use of force reported with the Smart Policing Digital Incident Reporting Form, aggregated by the gravity of the incidents" - missing

**Comment by brunosiqueira** [comment]
@ebadran essa issue ainda é válida para complementar o Usage Report ou o estado atual já atende?

**Comment by ebadran** [comment]
Acho que o usage report agora já atende e muito bem!
