### ISSUE TITLE
User Accounts with Three Access Permission Levels

### ISSUE THREAD

**Issue by ebadran** [igarape/copcast-admin#161]
System administrators may create user accounts with three access permission levels:
Level 1 users have permission to: 
     - View realtime locations of officers;
     - View history locations of officers and heatmaps;
     - View realtime footage;
Level 2 users have permission to all of the above, plus:
     - View history footage;
     - Export redacted footage (while video redaction is not ready, level 2 users may only view history footage);
     - View and download the CopCast Log Report;
     - Create Level 1 users;
Level 3 users also have permission to all of the above, plus:
     - Export of raw video footage;
     - Create Level 2 users;
     - Change data rentention periods.

**Comment by martelli** [comment]
We should also have de Level 0 profile, where the user can only send data (location, videos etc.) but have no access to the admin interface.
