### ISSUE TITLE
Log audit report

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#164]
Create a Log Audit Report by period using an append­-only data format to reduce the risk of tampering (?).
The system will produce an automated weekly report on access patterns across the set of approved individuals.

The report may also be generated by users with Levels 1 and 2 Access at any time.
The command to generate the report may be given from the "Admin Button" drop-down menu:

The report must present the history of user's actions of each action in the system.
eg:

![screen shot 2015-10-21 at 19 23 18](https://cloud.githubusercontent.com/assets/12832304/10650845/93df887a-782a-11e5-97cc-02ce5a3141ad.png)

Sd Ramos

 - 23/5/2015 12:04 - User logged in
 - 23/5/2015 12:10 - User started mission
 - 23/5/2015 12:15 - User started streaming
 - 23/5/2015 12:20 - User stopped mission

The report includes:
- How much total footage, by time and number of distinct pieces, has each user viewed in the last week;
- How much footage o​utside of known incidents,​ by time and number of distinct pieces, has each user viewed in the last week;
- Exact information on what videos have been exported within the last week;
- The hours of footage logged;
- The hours of footage accessed on the dashboard;
- The hours of footage accessed by (traffic police) officers on the phones;
- Any videos that have been viewed by 2+ different people within the last week.

**Comment by brunosiqueira** [comment]
What do you think @ebadran

**Comment by brunosiqueira** [comment]
@ebadran can we close this one since we have now better understanding of the audit report and the usage report?

**Comment by ebadran** [comment]
Yes, close it!
