### ISSUE TITLE
Cape Town Report for form incidents

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#165]
Create a report where the user can select a period and present all the incident forms from his group order by date. The report must present the same fields of the form

- Location, date and time
- Type of violation:
    - Accident (Y/N)
         - Gravity (from 1 to 5x)
         - Number of injured (input number)
    - Fine (Y/N)
         - Type of fine (select from a set of options)
    - Arrest (Y/N)
         - Resistance (Y/N)
               - Argument (Y/N)
               - Use of force (Y/N)
               - Use of lethal force (Y/N)

**Comment by salgado** [comment]
duplicate in #168
