### ISSUE TITLE
Log dashboard actions

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#169]
Each time an admin user executes one of the following actions, log to the history table:
 * log in to the dashboard
 * view one video at the history screen
 

Afterwards, insert this information in the report in Cape Town report log.

**Comment by brunosiqueira** [comment]
@jkosslyn and @ebadran 
I am thinking about how much registering for every video watching we should do. I am thinking about every time a admin user watches a video every hour or more. 

Eg: he watches a video, he watches it 5 minutes later, he watches two hours later - > we will have two registers in the histories table.

**Comment by jkosslyn** [comment]
I'd recommend logging everything as it happens. If something bad went down, it's best to have as much detail as possible when reconstructing the flow of events (including admin events)

**Comment by brunosiqueira** [comment]
OK, @jkosslyn 

I'll register every time, but will filter when showing in the log

**Comment by brunosiqueira** [comment]
@jkosslyn do you think we should have several logs for one video? In case the user plays/pauses the video
eg: 
video A - started to play at 00:15
video A - started to play at 00:35
video A - started to play at 01:18

**Comment by jkosslyn** [comment]
Yes, for auditing purposes it's better to get that granular. It doesn't need to always be shown in a default view but it's good for that data to be available if there's an investigation.

**Comment by ebadran** [comment]
Totally agree on logging everything. The question is what will be shown on
the standard report. Let's keep it as originally suggested by Justin:
report every time a user logs more than twice any footage that is not
flagged as an incident?
Em 03/12/2015 3:10 PM, "jkosslyn" <notifications@github.com> escreveu:

**Comment by martelli** [comment]
Moving the last requirement:

"Afterwards, insert this information in the report in Cape Town report log."

to #158 and closing the issue.
