### ISSUE TITLE
Ballon size to small

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#188]
![captura de tela 2015-12-07 as 15 50 07](https://cloud.githubusercontent.com/assets/28031/11634884/532f4fbe-9cfa-11e5-9318-631fd2f758e2.png)
![captura de tela 2015-12-07 as 14 55 15](https://cloud.githubusercontent.com/assets/28031/11634885/53508670-9cfa-11e5-8e2d-19d881b33984.png)

**Comment by brunosiqueira** [comment]
Still happening and showing vertical/horizontal rules

![captura de tela 2016-04-01 as 13 56 18](https://cloud.githubusercontent.com/assets/28031/14207389/a535c88e-f811-11e5-8370-c12533707872.png)

**Comment by brunosiqueira** [comment]
@arthurvasconcelos it is still happening (Chrome):

![captura de tela 2016-05-24 as 22 10 55](https://cloud.githubusercontent.com/assets/28031/15524955/69a3335a-21fc-11e6-8bbb-6471a3e349e6.png)

**Comment by arthurvasconcelos** [comment]
@brunosiqueira please check if the bug was fixed.

**Comment by brunosiqueira** [comment]
@arthurvasconcelos  the error only happens when the DEBUG bar is opened

![captura de tela 2016-06-01 as 16 29 47](https://cloud.githubusercontent.com/assets/28031/15722892/3d4cdeb2-2816-11e6-8fb4-6652a8a1731c.png)
