### ISSUE TITLE
Show different states in the streaming handshake

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#189]
In order to improve the feedback to the user while doing the handshake of the streaming, represent in the balloon its different steps:

Eg:
* Connecting to the server
* Authenticating with device
* Exchanging initial messages
* Connecting...

**Comment by martelli** [comment]
Related to copcast-android issue 35, thus places on the same sprint.

**Comment by dborkan** [comment]
Needs discussion, may no longer be necessary
