### ISSUE TITLE
Remove HTML5 controls from video

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#193]
Right now, in the history screen it is a little redundant: we have html5 controls in the video and the controls we created for playing it. We should remove the first ones.

**Comment by jkosslyn** [comment]
To clarify, keep the controls, just remove the timestamp from the video box. The "next video" control is very handy.

**Comment by brunosiqueira** [comment]
Actually the html controls involve only the ones inside the video. Play/Pause and timeline. The other buttons (outside the video) would stay.

**Comment by martelli** [comment]
I'd say only the "play" button is redundant. Perhaps removing it and reposition the "next video" and "previous video" 

![screenshot from 2016-01-07 15 41 54](https://cloud.githubusercontent.com/assets/239168/12177824/50adb2b2-b555-11e5-995a-5aff22c37b7b.png)

![suggestion_player](https://cloud.githubusercontent.com/assets/239168/12178000/41b24466-b556-11e5-83c1-02371f33ecd7.png)

**Comment by brunosiqueira** [comment]
Agreed, @martelli

**Comment by martelli** [comment]
How about this?

![screenshot from 2016-01-11 11 07 41](https://cloud.githubusercontent.com/assets/239168/12234370/aa0143d2-b853-11e5-9daa-8adb4e3e099a.png)

**Comment by martelli** [comment]
This one removes the user icon and places the video player above the timeline.

@ebadran @brunosiqueira 

![screenshot from 2016-01-11 11 21 23](https://cloud.githubusercontent.com/assets/239168/12234639/9902bd98-b855-11e5-8c5d-9240dc806da0.png)

**Comment by brunosiqueira** [comment]
The area above the timeline is important caus, when there are several
officers at that time, it show the icons of each one and allows the user to
change the curren users video.

Em segunda-feira, 11 de janeiro de 2016, Leandro Martelli <
notifications@github.com> escreveu:

> This one removes the user icon and places the video player above the
> timeline.
>
> @ebadran <https://github.com/ebadran> @brunosiqueira
> <https://github.com/brunosiqueira>
>
> [image: screenshot from 2016-01-11 11 21 23]
> <https://cloud.githubusercontent.com/assets/239168/12234639/9902bd98-b855-11e5-8c5d-9240dc806da0.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/igarape/copcast-admin/issues/193#issuecomment-170547305>
> .
>


-- 
Bruno Siqueira

**Comment by martelli** [comment]
Yep. Badran pointed that out. I came out with a mix of both, which has been commited.
