### ISSUE TITLE
Give tips over admin type

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#205]
Related to #161 

The user might not know/remember to which functionalities each admin level is allowed to execute. Present in the User creation/edition tips over the different types of admins

**Comment by brunosiqueira** [comment]
@arthurvasconcelos https://docs.google.com/document/d/13JqlGeBQSMWQ9U1oCf2oOCVcEn73FJeSva9AsPNVl6I/edit

**Comment by brunosiqueira** [comment]
We must internationalize the code

**Comment by arthurvasconcelos** [comment]
@brunosiqueira, you need to translate the text from the tip. Search for key "ROLE_TIP" in .po files.

**Comment by brunosiqueira** [comment]
@arthurvasconcelos: the tip does not disappear when we change tabs

![captura de tela 2016-06-02 as 19 01 43](https://cloud.githubusercontent.com/assets/28031/15762509/89027414-28f4-11e6-8619-a7f52a859379.png)
