### ISSUE TITLE
User search should not be case sensitive

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#225]
1 - paginate
2 - create a filter with a text box to search for name, login, email, etc.

**Comment by brunosiqueira** [comment]
@arthurvasconcelos The search is case sensitive. I search for "bruno" and it does not find results, since the name of the user is "Bruno"

**Comment by dborkan** [comment]
I have a fix for this in https://github.com/igarape/copcast-server/pull/69
