### ISSUE TITLE
Sign in modal not showing in Mobile Devices

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#229]
Maybe this happened after #194 correction.
When accessing the admin system from devices, the login modal is not showing up, and the sign out link do not appear

**Comment by arthurvasconcelos** [comment]
I checked this bug and it probably exists only in the branch [develop](https://github.com/igarape/copcast-admin/tree/develop). Using the branch [webrecorder](https://github.com/igarape/copcast-admin/tree/webrecorder) I tested three different devices and the bug did not happen.
