### ISSUE TITLE
Listbox with big names passes the limit

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#230]
in the docs.mycopcas.com instance, usernames are particularly big. In some listboxes, they pass the defined limit. We have to limit the with of the lists.
![captura de tela 2016-04-12 as 14 20 12](https://cloud.githubusercontent.com/assets/28031/14461376/2c2da1c6-00ba-11e6-809a-1a6466131fe0.png)
![captura de tela 2016-04-12 as 14 20 03](https://cloud.githubusercontent.com/assets/28031/14461377/2c2de834-00ba-11e6-9a0c-d69d4a9c4654.png)

**Comment by arthurvasconcelos** [comment]
This bug is restricted to the chrome browser for OS X.
