### ISSUE TITLE
Information over video sizes before/after upload

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#234]
We need to think about a way to clarify to the user that the files in the device will not reflect the uploaded files in the server, since it decreases their size after the upload processing

=====

In the Usage Report, below the Uploaded data Column, writ "compressed data"

**Comment by martelli** [comment]
Do you mean when checking the sizes shown in the reports?

**Comment by brunosiqueira** [comment]
I am showing in the log report now the amount of data uploaded (which is smaller than the one in the phone before the upload)

**Comment by brunosiqueira** [comment]
Now I show in the use report the amount relative to that data uploaded that
day.

Em quarta-feira, 13 de abril de 2016, Leandro Martelli <
notifications@github.com> escreveu:

> Do you mean when checking the sizes shown in the reports?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/igarape/copcast-admin/issues/234#issuecomment-209526433>
>


-- 
Bruno Siqueira
