### ISSUE TITLE
All Officers Button is Out of Position

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#247]
![unnamed](https://cloud.githubusercontent.com/assets/28031/15042536/c94e4f3c-12bc-11e6-9e45-2aa66c4a5f93.png)

**Comment by brunosiqueira** [comment]
@arthurvasconcelos  o botão está na frente da mensagem de desconexão. 
![captura de tela 2016-05-06 as 16 16 27](https://cloud.githubusercontent.com/assets/28031/15077370/091a8f9c-13a6-11e6-9b06-2b20ce26f890.png)

**Comment by arthurvasconcelos** [comment]
This bug was fixed in commit bc6a9505a6eac3cec11bab3b1f5b88bbf2e27cc6 along side issue #220.
