### ISSUE TITLE
New video player at History Screen

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#260]
![new_vid_1](https://cloud.githubusercontent.com/assets/28031/15376013/e3be1af2-1d28-11e6-94ae-49dc2a7b6008.png)

![new_vid_2](https://cloud.githubusercontent.com/assets/28031/15376019/ea7d5038-1d28-11e6-9759-b87e9a550f3f.png)

The image above represents a change we must do in the video player in the history screen. 

- move the user name up
- change the controls and hover event below
- present the "no audio" information

This are the messages in English and Portuguese:
- “Audio automatically disabled. Available only on  EXPORT.”
- “Áudio desativado automaticamente, disponível apenas na função ‘exportar'."

DATABASE: the user can select the close box and the message can now show anymore. For that, we decided to create a *settings* field in the *users* table. That field will have a Json inside with all the key/values necessary to register these information.

**Comment by arthurvasconcelos** [comment]
![screenshot from 2016-05-18 15 18 02](https://cloud.githubusercontent.com/assets/1286768/15370181/271adfc8-1d0c-11e6-9cf6-bf43a92892c5.png)

Change "of" to "or".

**Comment by brunosiqueira** [comment]
@arthurvasconcelos : don't forget to implement the video current time counter on the top-left of the video player

**Comment by arthurvasconcelos** [comment]
Fixed in commit 4408a1d54b2e450a7e0931bf1808b860a1289a78
