### ISSUE TITLE
When the client connection is lost, close the livestream modal window.

### ISSUE THREAD

**Issue by martelli** [igarape/copcast-admin#278]

**Comment by brunosiqueira** [comment]
The dialog stays open in both scenarios:
1. If the device looses connection
2. If the admin looses connection

![captura de tela 2016-06-10 as 12 44 40](https://cloud.githubusercontent.com/assets/28031/15970365/a217bcf4-2f0a-11e6-85dc-52f10b6b33a5.png)

**Comment by arthurvasconcelos** [comment]
@brunosiqueira i have tested in my local server and in dev server and this bug doesn't occour... please test this again... if possible have the chrome console opened to catch some possible strange error.

**Comment by arthurvasconcelos** [comment]
Apparently, removing the forced user registration the bugs in this issue and in the issue #287 have been fixed and now the socket normally controls the connection to the user.
