### ISSUE TITLE
Change password invalidates problem

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#28]
1 - enter site
2 - clicks forgot password
3 - types email
4 - write new password in field
Result: I got two problems 
     - Writing the correct new password, the login was not taking any effect
     - After logged, no data was coming from the server (users and groups)

It only logged when I opened a new browser instance.

**Comment by fcavalcantirj** [comment]
brow, nao consegui reproduzir...ainda procede esse bug? com qual login testou?

**Comment by brunosiqueira** [comment]
testei local com o meu login mesmo.
Você fez o passo-a-passo e funcionou?
