### ISSUE TITLE
Clock in history player must be based on timeline

### ISSUE THREAD

**Issue by arthurvasconcelos** [igarape/copcast-admin#280]
The disabled clock in history player must be based on the video time.

**Comment by brunosiqueira** [comment]
@arthurvasconcelos: 
@ebadran got an error with differences between the timeline time and the player time.
![screen shot 2016-06-10 at 11 34 44](https://cloud.githubusercontent.com/assets/28031/15969872/506ffa44-2f08-11e6-905a-c50bfb35784f.png)

**Comment by arthurvasconcelos** [comment]
@ebadran, i dont have access to this server... so can you check the same object (see the image below) and screenshot for me with the objects inside video property open. thanks.

![screenshot from 2016-06-10 17 42 01](https://cloud.githubusercontent.com/assets/1286768/15978226/28afacf4-2f33-11e6-87cc-f904733e2aa7.png)

**Comment by brunosiqueira** [comment]
@arthurvasconcelos descobrimos que o problema deste vídeo é que, na verdade, não existe localização no horário do vídeo, então ele mantém o marcador na última localização registrada naqueles dia.

Vamos fazer a seguinte mudança na timeline: quando possuir um vídeo que não possui localização associada, incluir o marcador azul da timeline no horário de início do vídeo. O mapa não exibirá marcador nenhum.
