### ISSUE TITLE
Error "Can't play this this video." after clicking play on Video playback Android screen

### ISSUE THREAD

**Issue by dborkan** [igarape/copcast-admin#285]
To replicate, login on Android (using dev-api.mycopcast.com as the server), record a video, then go to "Video playback" and hit play on the video.  Then I see this error:
![screenshot_20160606-113737](https://cloud.githubusercontent.com/assets/6494307/15827929/5ce2e6cc-2bdb-11e6-9aef-201ecb4b4ca6.png)

**Comment by brunosiqueira** [comment]
Duplicated from igarape/copcast-android/issues/166

**Comment by dborkan** [comment]
OK - we can close this issue since it's duplicate
