### ISSUE TITLE
Video Speedup on the History Screen

### ISSUE THREAD

**Issue by arthurvasconcelos** [igarape/copcast-admin#288]
@ebadran commented on [Mon Oct 26 2015](https://github.com/igarape/copcast-server/issues/49)

When reviewing flagged or incident footage (e.g. for a criminal investigation, or a disciplinary measure against an officer) a video speedup feature may be enabled to allow users to skim through footage at 2x, 4x, 8x speed.

**Comment by brunosiqueira** [comment]
@arthurvasconcelos : update the speed options accordingly with youtube speed.

**Comment by arthurvasconcelos** [comment]
Done.

![screenshot from 2016-06-10 17 36 35](https://cloud.githubusercontent.com/assets/1286768/15978050/42940a12-2f32-11e6-8d4d-0f9ddc79f821.png)
