### ISSUE TITLE
Search bar in realtime stopped working

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#289]
The field should filter users by name, username and groups by name

![captura de tela 2016-06-10 as 12 41 09](https://cloud.githubusercontent.com/assets/28031/15969985/d2f02020-2f08-11e6-80eb-7122c1fb34fb.png)

**Comment by brunosiqueira** [comment]
The "All Officers" button should fit only the filtered users

**Comment by dborkan** [comment]
I fixed filtering based on user name or login in https://github.com/igarape/copcast-admin/commit/444234ba727679f31296b78426120b580abef856

For filtering by group however, the server doesn't send the group name to the admin over websocket (it's missing from here https://github.com/igarape/copcast-server/blob/webrecorder/lib/heartbeats/index.js#L20).  I can easily add the groupId, but I'm not sure how to add the group name without hitting the database.  Any ideas?  Or is there a way to easily map from groupId to groupName in the admin without making another request?

**Comment by dborkan** [comment]
I now have the copcast-admin code updated to fix filtering, with changes to send the group name in the 'users:heartbeat' websocket message here: https://github.com/igarape/copcast-server/pull/85
