### ISSUE TITLE
Create timeout in connection problems

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#292]
If an admin user is watching a live streaming video and there's a connection problems, wait for a minute before closing the live streaming window. Send a notification warning that there are connection problems

**Comment by dborkan** [comment]
I've been working on this and using a modified android app and server have it working where video streaming can resume after a reconnect.  I'm testing by streaming from my phone while connected to WiFi - then if I disconnect the WiFi the socket is interrupted by 5-10 seconds while it reconnects over 4G.  When video resumes there is a slight fast-forward effect but it only lasts maybe 1 second and then is back to streaming with little delay.

I'll work on cleaning this up and create some pull requests soon
