### ISSUE TITLE
Emmiters in the correct groups

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#306]
"When I'm logged in as a Level1 user, I can only see users from my own group √.
If a user from a different group ends a mission, I get the message ""Undefined is no longer connected""."

**Comment by martelli** [comment]
Closing with a workaround solution.
The definitive solution will be by implementing the heartbeat via websockets.

**Comment by brunosiqueira** [comment]
Closed since the connection was redone from scratch
