### ISSUE TITLE
Marker not showing up on realtime screen

### ISSUE THREAD

**Issue by dborkan** [igarape/copcast-admin#312]
I am currently streaming (using the webrecorder build from July 6, 2016).  I have 2 windows open for https://dev.mycopcast.com/#/ - the 1st window has been open for over an hour, but it does not show any realtime marker.  When I opened a 2nd window for the same realtime URL, the realtime marker appears.

When I refreshed the original window, the marker appeared

**Comment by dborkan** [comment]
I'm seeing this now while streaming even on windows I've just opened.  I don't see any errors on the server, however I do see this trace repeatedly from the admin JavaScript console:
![screen shot 2016-07-07 at 11 57 02 am](https://cloud.githubusercontent.com/assets/6494307/16659895/11dd2954-443a-11e6-9896-ad67a7ea4f0b.png)

**Comment by dborkan** [comment]
For some reason this is very easy for me to replicate on the https://dev.mycopcast.com/#/ server/admin (where I always see the "WebScket is closed before the connection is established" error, but I can't replicate on my own server/admin.  Also sometimes if I leave the dev server admin console running long enough, the error corrects itself

**Comment by dborkan** [comment]
From http://stackoverflow.com/questions/12487828/what-does-websocket-is-closed-before-the-connection-is-established-mean/12503628#12503628:
```
In this code what it means is that ws.close() was called (by user code) before the connection was even given a chance to be established.

So, the cause of this error is if code attempts to close the WebSocket connection before it's had a chance to actually connect.
```

**Comment by martelli** [comment]
This must be due to the very tight timing I've set. I'll relax it a bit and see how it behaves.
