### ISSUE TITLE
User missing from realtime screen with warning "User not active yet"

### ISSUE THREAD

**Issue by dborkan** [igarape/copcast-admin#313]
Seen testing with both my server and admin running on a DigitalOcean machine.

I am currently recording on my phone, however the realtime admin screen does not show a marker for me.   Instead I repeatedly see the "User not active yet." trace, which seems to indicate that a heartbeat was received before we had other information about the user.

I've left this window running for 5+ minutes and this trace keeps appearing and the screen hasn't correct itself.  However in other windows for the same server it is working fine (maybe some kind of race condition?)

![screen shot 2016-07-08 at 5 57 18 pm](https://cloud.githubusercontent.com/assets/6494307/16702646/71d1ffc8-4535-11e6-891e-1aacc21606f4.png)

**Comment by dborkan** [comment]
I see that in this case the "listing" trace is missing, which appears in the successful cases.  This indicates that the ```receiveBroadcastersList``` function was not called - meaning we never got the user list, which would explain why loaduser failed.

**Comment by martelli** [comment]
This is related to the establishing of the websocket connection.
I've relaxed the timings a bit. Let's see how it behaves now.

**Comment by martelli** [comment]
Ok, found it. The fetching of user information must occur right after the connection is established.
