### ISSUE TITLE
Compress videos before uploading them

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#5]

**Comment by brunosiqueira** [comment]
Check this library: http://developer.android.com/reference/java/util/zip/Deflater.html

**Comment by salgado** [comment]
app	resolução	tempo gravação	tamanho do vídeo
galaxy s4	1920x1080	10	21mb
galaxy s5	1280x720	11	16mb
galaxy s6	640x480	10	3,8mb
galaxy s7	320x240	10	1,1MB
cocast	176x144	15	949kb
copcast	176x144	10	630kb
copcast alterando size mas resolução piorou	640x480	10	630kb
