### ISSUE TITLE
History - Keyboard focus

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#66]
Keyboard focus flow between the different input boxes (i.e. user selection, calendar, etc.) must be improved to be more intuitive;

**Comment by arthurvasconcelos** [comment]
@brunosiqueira 

So, I've been testing sort with tabindex property, but this is just causing a bug in tab navigation. Causing elements non accessible through tab.

Besides that, when I tryed navigate between the page elements with tab, seemed very fluid to me...

Can we talk more about that?
