### ISSUE TITLE
UploadService out of memory

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-admin#73]
java.lang.RuntimeException: An error occured while executing doInBackground()
1	at android.os.AsyncTask$3.done(AsyncTask.java:300)
2	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
3	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
4	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
5	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
6	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
7	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
8	at java.lang.Thread.run(Thread.java:841)
9	Caused by: java.lang.OutOfMemoryError
10	at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:94)
11	at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:145)
12	at java.lang.StringBuffer.append(StringBuffer.java:219)
13	at com.splunk.mint.network.io.OutputStreamMonitor.updateBody(OutputStreamMonitor.java:67)
14	at com.splunk.mint.network.io.OutputStreamMonitor.write(OutputStreamMonitor.java:58)
15	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:131)
16	at java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:231)
17	at com.android.okhttp.internal.http.RetryableOutputStream.writeToSocket(RetryableOutputStream.java:73)
18	at com.android.okhttp.internal.http.HttpTransport.writeRequestBody(HttpTransport.java:112)
19	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:638)
20	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
21	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
22	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
23	at org.igarape.copcast.utils.MultipartUtility.finish(MultipartUtility.java:149)
24	at org.igarape.copcast.utils.NetworkUtils$1.doInBackground(NetworkUtils.java:146)
25	at org.igarape.copcast.utils.NetworkUtils$1.doInBackground(NetworkUtils.java:131)
26	at android.os.AsyncTask$2.call(AsyncTask.java:288)
27	at java.util.concurrent.FutureTask.run(FutureTask.java:237)

**Comment by fcavalcantirj** [comment]
to ligado....deixei anotado isso

2015-07-01 11:23 GMT-03:00 Bruno Siqueira <notifications@github.com>:

**Comment by salgado** [comment]
User SD1: After 1 day of use, screen with 0 bytes to send data, but no video display in the admin.
- User SD2: After 1 day of use, screen with 32MB of data to send, failed to pass after clicking send data and location appears only in a 3 hour period.
